### ISSUE TITLE
blank window for every example on Ubuntu 20.04 with Intel graphics

### ISSUE THREAD

**Issue by DevinBayly** [nannou-org/nannou#706]
I originally added a comment below a similar post that has now been resolved. The fix for issue #698 didn't work for me so I'm leaving this issue here. 

I have Intel® HD Graphics 4000 (IVB GT2) which is Ivy bridge, and the error message that I get when I try to run 
``` cargo run --release --example draw``` or any other example is 
```
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
```

I've tried installing the oibaf drivers, with this
```
sudo add-apt-repository ppa:oibaf/graphics-drivers
sudo apt update
sudo apt upgrade
```

and then restarting the machine, but the error stays the same.

Any help with this would be very welcome, I want to use nannou but haven't been able to.

**Comment by johnniehard** [comment]
Having the same issue. When I first tried out nannou in early january everything worked fine. Now the code I wrote then only shows a blank window.
I'm also on Ubuntu 20.04.

**Comment by danwilhelm** [comment]
Could you try this:
> In nannou/src/frame/mod.rs, change the line pub const DEFAULT_MSAA_SAMPLES: u32 = 4; from 4 to 1.

Mid-December, some of the examples stopped working on Macs as well (see #719) -- could be the same issue.

**Comment by johnniehard** [comment]
I just tried running the examples from the master branch and they work fine.
```
cargo run --release --example draw
```
But projects with `nannou = "0.15"` in `Cargo.toml` have the blank window issue. Maybe it's time to do a new release to crates.io?

I'm trying to do a git bisect to figure out which commit fixes the issue, but compiling is taking forever so we'll see how it goes :)

**Comment by johnniehard** [comment]
Leaving the attempt at performing a git bisect, a lot of the commits between last crates.io release (2020-10-04) and now fails to compile with this output:
```
error[E0282]: type annotations needed
  --> /home/johnnie/.cargo/registry/src/github.com-1ecc6299db9ec823/sample-0.9.1/src/window.rs:73:41
   |
73 |         let v = phase.to_float_sample().to_sample() * PI_2;
   |                                         ^^^^^^^^^ cannot infer type for type parameter `S` declared on the associated function `to_sample`
   |
help: consider specifying the type argument in the method call
   |
73 |         let v = phase.to_float_sample().to_sample::<S>() * PI_2;
   |                                                  ^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0282`.
error: could not compile `sample`

```
@mitchmindtree I think that a new version should be pushed to crates.io, since the issue is fixed in the current master, even though it bothers me personally to not be able to pinpoint exactly what fixes the issue :).

**Comment by mitchmindtree** [comment]
@johnniehard thanks for digging into this!

I've noticed the same problem with projects depending on `0.15` as of a week or two ago. I'm still unsure whether the issue was introduced when I updated my OS/packages (I'm on NixOS running GNOME) or if it was caused by an update to one of the crate dependencies of wgpu 0.5.

Either way, I do agree it would be nice to publish what's currently pending on master. My only concern is that we've had a few reports of serious issues on macOS as of the wgpu 0.6 update on master, and I'm thinking we should address these first. @danwilhelm has made a few interesting discoveries in #719.

And yes I think that `sample` crate compile error was only introduced in a recent-ish rustc version (though I could be wrong), but yes, it has made it tricky to bisect recent errors :facepalm:

**Comment by johnniehard** [comment]
I just found that you can specify a git repo as source for a dependency:
```
nannou = { git = "https://github.com/nannou-org/nannou" }
```
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories

Which means I can work around the issue for now.

**Comment by DevinBayly** [comment]
Jumping back in after a lengthy radio silence. 

I no longer have this issue with the basic --draw example. I did however start completely over from where I was last. 

I went back to the platform specific setup and did
```
sudo add-apt-repository ppa:oibaf/graphics-drivers
sudo apt-get update
sudo apt-get upgrade
```
and then 
```
sudo apt-get install libvulkan1 mesa-vulkan-drivers vulkan-utils
``` 

Of note is that the last command normally says "cannot find libvulkan1" or something, but that was no longer the case. 

After cloning and running 
```
cargo run --release --example draw
``` 
I get the example window and the familiar vulkan message `MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete` but things seem ok? 

Sorry if this is a tangent from the point the issue discussion has reached, I just wanted to weigh back in.

**Comment by mitchmindtree** [comment]
@DevinBayly thanks for sharing - I think if anything this further suggests that the issue is more than likely in nannou `0.15` (and wgpu 0.5 or one of its dependencies) but seems to have been fixed on master (likely in the update from wgpu 0.5 to 0.6).

> I get the example window and the familiar vulkan message MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete but things seem ok?

Yeah I've had that something along the lines of that message for a while (though on NixOS), but things seem to work at least :)

Fwiw, I'm currently looking into updating to wgpu 0.7. I'm hoping that the new validation checks will help to work out what's going on for these latest macos crashes, and in turn get us closer to publishing a new version of nannou.

**Comment by mitchmindtree** [comment]
OK, I think this has been fixed in the latest version of wgpu which we updated to in #726 and just published in nannou 0.16.0. Feel free to re-open if you still have issues.
